#!/usr/bin/env python3
"""Compare combined TPC-H + TPC-DS profiling results against augmentation targets.

Parses the report.md files generated by digest_profile.py.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Text columns that indicate text-based aggregation targets
TEXT_COLS = [
    "i_item_id", "i_brand", "i_category", "i_class", "i_manufact",
    "s_store_name", "s_state", "s_company_name",
    "c_last_name", "c_customer_id", "c_first_name",
    "ca_city", "ca_state", "ca_zip", "ca_county",
    "cd_gender", "cd_education_status",
    "w_warehouse_name", "sm_type", "sm_carrier",
    "r_reason_desc", "cc_name", "p_promo_name",
    "ship_mode", "part_name", "nation", "cntrycode",
    "l_shipmode", "o_clerk",
]


def _section(text: str, heading: str) -> str:
    """Extract a markdown section from ## heading to next ## or EOF."""
    pat = re.compile(rf"^## {re.escape(heading)}.*?(?=\n## |\Z)", re.DOTALL | re.MULTILINE)
    m = pat.search(text)
    return m.group() if m else ""


def _table_rows(section: str) -> list[list[str]]:
    """Extract rows from a markdown table (skip header and separator)."""
    rows = []
    lines = section.split("\n")
    in_table = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if not in_table:
                in_table = True  # header row
                continue
            if cells and all(c.replace("-", "").replace(":", "") == "" for c in cells):
                continue  # separator row
            if cells and cells[0].startswith("**"):
                continue  # summary row
            if cells and cells[0].startswith("Q"):
                rows.append(cells)
        elif in_table and not stripped:
            break  # end of table
    return rows


def parse_report(path: Path) -> dict:
    """Parse a digest report.md into structured data."""
    text = path.read_text(encoding="utf-8")
    result: dict = {
        "query_count": 0,
        "joins_per_query": {},      # qnum -> set of join kinds (LEFT, RIGHT, INNER, etc.)
        "null_per_query": {},       # qnum -> set of patterns
        "skew_per_query": {},       # qnum -> "High"/"Moderate"/"Low"
        "depth_per_query": {},      # qnum -> int
        "ops_per_query": {},        # qnum -> int
        "agg_funcs_per_query": {},  # qnum -> set of functions
        "agg_targets_per_query": {},# qnum -> str (targets text)
    }

    # --- Query Characteristics ---
    sec = _section(text, "Query Characteristics")
    for cells in _table_rows(sec):
        # | Q1 | Workload Mix | CTAS | Metadata | Maintenance | Subqueries | Operator Count | Expression Depth |
        if len(cells) >= 8:
            qnum = cells[0]
            try:
                ops = int(cells[6])
                depth = int(cells[7])
            except ValueError:
                continue
            result["ops_per_query"][qnum] = ops
            result["depth_per_query"][qnum] = depth
            result["query_count"] += 1

    # --- Join Analysis ---
    sec = _section(text, "Join Analysis")
    for cells in _table_rows(sec):
        # | Q1 | INNER HASH_JOIN, LEFT HASH_JOIN | surrogate/FK |
        if len(cells) >= 2:
            qnum = cells[0]
            types_str = cells[1].strip()
            kinds = set()
            if types_str and types_str != "—":
                for jt in types_str.split(","):
                    jt = jt.strip()
                    if jt:
                        kind = jt.split()[0].upper()
                        kinds.add(kind)
            result["joins_per_query"][qnum] = kinds

    # --- Data Characteristics ---
    sec = _section(text, "Data Characteristics")
    for cells in _table_rows(sec):
        # | Q1 | — | IS NOT NULL | High (4/11 ops >10× off) |
        if len(cells) >= 4:
            qnum = cells[0]
            null_str = cells[2].strip()
            skew_str = cells[3].strip()

            patterns = set()
            for p in ["IS NOT NULL", "IS NULL", "COALESCE", "NULLIF"]:
                if p in null_str:
                    patterns.add(p)
            result["null_per_query"][qnum] = patterns

            if "High" in skew_str:
                result["skew_per_query"][qnum] = "High"
            elif "Moderate" in skew_str:
                result["skew_per_query"][qnum] = "Moderate"
            else:
                result["skew_per_query"][qnum] = "Low"

    # --- Aggregation Analysis ---
    sec = _section(text, "Aggregation Analysis")
    for cells in _table_rows(sec):
        # | Q1 | AVG, COUNT, MIN, SUM | *, COALESCE, l_discount, ... |
        if len(cells) >= 3:
            qnum = cells[0]
            funcs_str = cells[1].strip()
            targets_str = cells[2].strip()

            funcs = set()
            if funcs_str and funcs_str != "—":
                for fn in funcs_str.split(","):
                    fn = fn.strip().upper()
                    if fn:
                        funcs.add(fn)
            result["agg_funcs_per_query"][qnum] = funcs
            result["agg_targets_per_query"][qnum] = targets_str

    return result


def main() -> None:
    tpch_report = ROOT / "TPC-H" / "logs" / "duckdb" / "sf1" / "profile" / "report.md"
    tpcds_report = ROOT / "TPC-DS" / "logs" / "duckdb" / "sf1" / "profile" / "report.md"

    data_list = []
    labels = []
    for path, label in [(tpch_report, "TPC-H"), (tpcds_report, "TPC-DS")]:
        if path.exists():
            data_list.append(parse_report(path))
            labels.append(label)

    if not data_list:
        print("No report.md files found. Run profiling + digest first.")
        return

    # Merge all data
    total_queries = sum(d["query_count"] for d in data_list)

    # --- Outer joins ---
    outer_queries = 0
    join_kind_counts: dict[str, int] = {}
    for d in data_list:
        for qnum, kinds in d["joins_per_query"].items():
            has_outer = any(k in ("LEFT", "RIGHT", "FULL") for k in kinds)
            if has_outer:
                outer_queries += 1
            for k in kinds:
                join_kind_counts[k] = join_kind_counts.get(k, 0) + 1

    # --- Null handling ---
    null_pattern_counts: dict[str, int] = {}
    queries_with_any_null = 0
    for d in data_list:
        for qnum, patterns in d["null_per_query"].items():
            if patterns:
                queries_with_any_null += 1
            for p in patterns:
                null_pattern_counts[p] = null_pattern_counts.get(p, 0) + 1

    # --- Skew ---
    skew_counts: dict[str, int] = {"High": 0, "Moderate": 0, "Low": 0}
    for d in data_list:
        for qnum, level in d["skew_per_query"].items():
            skew_counts[level] = skew_counts.get(level, 0) + 1

    # --- Depth & ops ---
    all_depths: list[int] = []
    all_ops: list[int] = []
    for d in data_list:
        all_depths.extend(d["depth_per_query"].values())
        all_ops.extend(d["ops_per_query"].values())

    # --- Aggregation ---
    all_agg_funcs: dict[str, int] = {}
    text_agg_queries = 0
    for d in data_list:
        for qnum, funcs in d["agg_funcs_per_query"].items():
            for fn in funcs:
                all_agg_funcs[fn] = all_agg_funcs.get(fn, 0) + 1
        for qnum, targets in d["agg_targets_per_query"].items():
            targets_lower = targets.lower()
            if any(tc in targets_lower for tc in TEXT_COLS):
                text_agg_queries += 1

    # --- Output ---
    print(f"# Combined Augmentation Evaluation\n")
    parts = [f"{l}: {d['query_count']}" for d, l in zip(data_list, labels)]
    print(f"**Total queries**: {total_queries} ({', '.join(parts)})\n")

    outer_pct = 100 * outer_queries / total_queries if total_queries else 0
    print("## Join Analysis")
    print(f"| Metric | Value | Target |")
    print(f"|:-------|------:|-------:|")
    print(f"| Queries with outer joins (plan) | {outer_queries}/{total_queries} ({outer_pct:.0f}%) | 37% |")
    for jt in sorted(join_kind_counts, key=join_kind_counts.get, reverse=True):
        print(f"| {jt} joins | {join_kind_counts[jt]} queries | — |")
    print()

    null_any_pct = 100 * queries_with_any_null / total_queries if total_queries else 0
    print("## Null Handling")
    print(f"| Pattern | Queries | % |")
    print(f"|:--------|--------:|--:|")
    for pattern in ["COALESCE", "IS NOT NULL", "IS NULL", "NULLIF"]:
        cnt = null_pattern_counts.get(pattern, 0)
        pct = 100 * cnt / total_queries if total_queries else 0
        print(f"| {pattern} | {cnt} | {pct:.0f}% |")
    print(f"| **Any null handling** | **{queries_with_any_null}** | **{null_any_pct:.0f}%** |")
    print()

    print("## Expression Depth")
    deep = sum(1 for d in all_depths if d > 10)
    deep_pct = 100 * deep / len(all_depths) if all_depths else 0
    print(f"| Range | Queries | % |")
    print(f"|:------|--------:|--:|")
    for lo, hi, label in [(1, 5, "1-5"), (6, 10, "6-10"), (11, 20, "11-20"), (21, 50, "21-50"), (51, 9999, "51+")]:
        cnt = sum(1 for d in all_depths if lo <= d <= hi)
        pct = 100 * cnt / len(all_depths) if all_depths else 0
        print(f"| {label} | {cnt} | {pct:.0f}% |")
    print(f"| **Depth > 10** | **{deep}** | **{deep_pct:.0f}%** (target: 12%) |")
    print()

    print("## Operator Count")
    print(f"| Range | Queries | % |")
    print(f"|:------|--------:|--:|")
    for lo, hi, label in [(1, 10, "1-10"), (11, 20, "11-20"), (21, 50, "21-50"), (51, 100, "51-100"), (101, 99999, "101+")]:
        cnt = sum(1 for o in all_ops if lo <= o <= hi)
        pct = 100 * cnt / len(all_ops) if all_ops else 0
        print(f"| {label} | {cnt} | {pct:.0f}% |")
    heavy = sum(1 for o in all_ops if o > 100)
    heavy_pct = 100 * heavy / len(all_ops) if all_ops else 0
    print(f"| **101+ ops** | **{heavy}** | **{heavy_pct:.0f}%** (target: 13%) |")
    print()

    print("## Aggregation Functions")
    print(f"| Function | Queries |")
    print(f"|:---------|--------:|")
    for fn, cnt in sorted(all_agg_funcs.items(), key=lambda x: -x[1]):
        print(f"| {fn} | {cnt} |")
    print()

    text_pct = 100 * text_agg_queries / total_queries if total_queries else 0
    print("## Text Aggregation")
    print(f"| Metric | Value | Target |")
    print(f"|:-------|------:|-------:|")
    print(f"| Queries with text agg targets | {text_agg_queries}/{total_queries} ({text_pct:.0f}%) | 34% |")
    print()

    high_skew = skew_counts.get("High", 0)
    high_pct = 100 * high_skew / total_queries if total_queries else 0
    print("## Data Skew")
    print(f"| Level | Queries | % |")
    print(f"|:------|--------:|--:|")
    for level in ["High", "Moderate", "Low"]:
        cnt = skew_counts.get(level, 0)
        pct = 100 * cnt / total_queries if total_queries else 0
        print(f"| {level} | {cnt} | {pct:.0f}% |")
    print()

    # --- Coverage Summary ---
    print("## Coverage Summary")
    print(f"| Target | Achieved | Target Value | Status |")
    print(f"|:-------|:---------|:-------------|:-------|")
    coalesce_pct = 100 * null_pattern_counts.get("COALESCE", 0) / total_queries if total_queries else 0
    is_not_null_pct = 100 * null_pattern_counts.get("IS NOT NULL", 0) / total_queries if total_queries else 0
    checks = [
        ("Outer Joins", f"{outer_pct:.0f}%", "37%", outer_pct >= 30),
        ("Expression Depth >10", f"{deep_pct:.0f}%", "12%", deep_pct >= 10),
        ("COALESCE usage", f"{coalesce_pct:.0f}%", "High freq", coalesce_pct >= 40),
        ("IS NOT NULL usage", f"{is_not_null_pct:.0f}%", "High freq", is_not_null_pct >= 30),
        ("Text Aggregation", f"{text_pct:.0f}%", "34%", text_pct >= 25),
        ("High Data Skew", f"{high_pct:.0f}%", "High", high_pct >= 40),
        ("101+ Operators", f"{heavy_pct:.0f}%", "13%", heavy_pct >= 2),
        ("Diverse Agg Functions", f"{len(all_agg_funcs)} types", ">=5 types", len(all_agg_funcs) >= 5),
    ]
    for name, achieved, target, passed in checks:
        status = "PASS" if passed else "PARTIAL"
        print(f"| {name} | {achieved} | {target} | {status} |")


if __name__ == "__main__":
    main()
